### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by loviswater** [NebulousLabs/Sia-GPU-Miner#35]
etminer@ETminerII:~/Sia/Sia-GPU-Miner$ make
cc -c -std=c11 -Wall -pedantic -O2 -o sia-gpu-miner.o sia-gpu-miner.c
sia-gpu-miner.c:18:19: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
                   ^
compilation terminated.
Makefile:20: recipe for target 'sia-gpu-miner.o' failed
make: **\* [sia-gpu-miner.o] Error 1

**Comment by DavidVorick** [comment]
I think that this is happening because you don't have the opencl libs installed on your computer.

What platform are you using?

**Comment by lpedretti** [comment]
I'm on ubuntu 14.04, i could try installing amd's opencl, is that what is needed or is there another opencl distribution to use?
Thanx!

**Comment by DavidVorick** [comment]
My understanding is that any standards-complient opencl implementation would be sufficient.

This is a very old issue, if you are having trouble can you open a new one?
