### ISSUE TITLE
OpenCL error when running binary

### ISSUE THREAD

**Issue by pmknutsen** [NebulousLabs/Sia-GPU-Miner#37]
$ ./sia-gpu-miner 
./sia-gpu-miner: /usr/lib/x86_64-linux-gnu/libOpenCL.so.1: no version information available (required by ./sia-gpu-miner)
Initializing...
Failed to get number of OpenCL platforms with error code -1001 (clGetPlatformIDs).

Ubuntu 14.04:
nvidia-opencl-icd-346
nvidia-libopencl1-346
opencl-headers (assume this is not required...)

**Comment by DavidVorick** [comment]
Some other people on ubuntu were having the same problem. I think you are missing a library. If you figure out what you need to install, can you let us know and we'll add it to the readme.

**Comment by GrumpyBear57** [comment]
This worked for me on Ubuntu 15.04 with the 346.96 nvidia driver (gtx 970)
http://askubuntu.com/questions/541114/how-to-make-opencl-work-on-14-10-nvidia-331-89-drivers
