### ISSUE TITLE
Installing gpu miner on server and have it send mined coins to wallet?

### ISSUE THREAD

**Issue by nixoye** [NebulousLabs/Sia-GPU-Miner#40]
is it possible to have siacoins mined on a server i own and have it send the coins to my wallet?

**Comment by JoshVorick** [comment]
The easiest way to do this is to just run an instance of siad on the server and have the miner send it to that wallet. Then you can either copy the wallet keys to your local wallet, giving you access to them, or simply send your earnings to your local wallet via a transaction.

Hope that helps!
