### ISSUE TITLE
HTTP error 404

### ISSUE THREAD

**Issue by wkshare** [NebulousLabs/Sia-GPU-Miner#58]
i running program: ./sia-gpu-miner

show information:
./sia-gpu-miner
Initializing...

HTTP error 404
HTTP error 404
...

my system:  MAC OS X 10.11.6 (15G31)
Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

**Comment by wkshare** [comment]
my wallet unclock

```
curl -i -A "Sia-Agent" -X POST localhost:9980/wallet/unlock?encryptionpassword=
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Date: Mon, 22 May 2017 13:41:39 GMT
Content-Length: 82

{"message":"error when calling /wallet/unlock: wallet has already been unlocked"}

```

my siad running
`
  501  1723  1722   0  5:11PM ??        28:54.92 /Users/wangkai/workspace/Sia-UI/Sia-UI.app/Contents/Resources/app/Sia/siad --api-addr=localhost:9980 --host-addr=:9982 --rpc-addr=:9981 --modules=cghrtw --sia-directory=/Users/wangkai/Library/Application Support/Sia-UI/sia`

@DavidVorick  help

**Comment by avahowell** [comment]
You have to run `siad` with the `miner` module. See `siad --modules` for info

**Comment by wkshare** [comment]
--modules=cghrtw change to --modules=cghrtwm
cghrtw is default parameters

is okay ?  @johnathanhowell

**Comment by avahowell** [comment]
yes, that looks good

**Comment by wkshare** [comment]
OK. im okay.  thks again.   @johnathanhowell
