### ISSUE TITLE
Uses only 1 gpu in system.

### ISSUE THREAD

**Issue by Karasur** [NebulousLabs/Sia-GPU-Miner#6]
Uses only 1 gpu in system, need cmd option to set platform_id and device_id.

**Comment by DavidVorick** [comment]
Thanks.

If you know anything about GPU dev, we'd appreciate some help. Otherwise, it might take us a few days or weeks to get to this.

**Comment by DavidVorick** [comment]
you can now select which gpu the miner uses, you can use multiple gpus by running multiple instances of the miner
