### ISSUE TITLE
What is Siad - ERROR 404

### ISSUE THREAD

**Issue by mdl6923** [NebulousLabs/Sia-GPU-Miner#77]
I am new to this and unfamiliar as to what Siad refers to. Is it the Sia-UI, the Sia GPU miner, or something else? I am trying to mine and I am fully synchronized in Sia-UI. When I type "miner" into the terminal it returns the message "Could not get miner status: API call not recognized: /miner"

When I open the miner application it just says ERROR 404 over and over. There were other users reporting the same issue, and someone responded to the issue with the following:

"2) Make sure you have a recent version of Sia installed and running. You must run Sia with the `miner` module enabled, which is not enabled by default in `Sia-UI`. To run with the miner module, use `siad`'s `-M` flag and specify the `m` module. See `siad modules`."

This brings me to my original question... what is siad referring to? What are siad modules? How do I specify the -M flag? Any help with this is much appreciated.

**Comment by ploth** [comment]
I'm also new to this. I started yesterday downloading the chain and it was completely downloaded in the morning. I have the `HTTP ERROR 404` too. I figured out that there is a `siad` and `siac` binary in `<YOURSIAFODLER>/resources/app/Sia`. There you can run the daemon `siad` with specific modules. IMHO the `siad` call should look like this `./siad -M gctwm`. At least the miner started to complain `HTTP ERROR 404 - check that the wallet is unlocked`. I couldn't figure out how to start the client (`siac`) to unlock the wallet so I started the `Sia-UI` again. But then unfortunately the client is uninitialized and has to redownload the entire chain. :cry: I have no idea whether it will work after this or not.

**Comment by DavidVorick** [comment]
@ploth you can unlock the wallet with `siac wallet unlock`

If you are getting a `404` error when running the miner, it means you haven't enabled the mining module in `siad`. You can enable it with `siad -M gctwm`

**Comment by ploth** [comment]
Just to give a small update for @mdl6923   
It worked for me.  
Just have a look at `<YOURSIAFODLER>/resources/app/Sia`  
Start it with `./siad -M gctwm`  
And then start the Sia_UI

**Comment by mdl6923** [comment]
@ploth Thanks so much for the help. I am still having trouble understand where/how to put the ./siad -M gctwm. I have the folder open but don't know where to go from there...

**Comment by mdl6923** [comment]
@ploth this is what is says when I open the application titled "siad" in resources>app>Sia

This is a command line tool.

You need to open cmd.exe and run it from there.

**Comment by mdl6923** [comment]
And then when I open my computer's command prompt and enter "./siad -M gctwm" it leaves me with this...

H:\>./siad -M gctwm
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ploth** [comment]
Sorry @mdl6923 It looks like your are on Windows. I can't help you with that.
